[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"
  REACT_APP_API_URL = "https://stopmeet-api.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run start"
  port = 3000
  publish = "build"
